# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-20 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0008_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='lyrics_text',
            field=tinymce.models.HTMLField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='song',
            name='lang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lang', to='songs.Language'),
        ),
    ]
