# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-25 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0009_auto_20161120_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='lyrics_text',
            field=models.TextField(),
        ),
    ]
